#!/usr/bin/env python

import argparse
import os

RSYNC = "rsync -e ssh -avzl --progress --delete"

def sync(direction, host, path=None, dry_run=False, delete=False):
    """
    Sync the eBOSS measurements

    Parameters
    ----------
    direction : {'to', 'from'}
        the direction to do the transfer, either 'to' or 'from'
        the remote host
    host : {'cori', 'edison'}
        the name of the remote host
    path : str
        a subpath from the ``RSDFIT_FITS`` directory
    dry_run : bool, optional
        whether to do a dry-run
    delete : bool, optional
        whether to delete files when syncing
    """
    # the command + options
    if not delete:
        cmd = [RSYNC.split('--delete')[0]]
    else:
        cmd = [RSYNC]
    cmd += ["--exclude='info'", "--exclude='plots'", "--exclude='.*'"]
    if dry_run: cmd.append('--dry-run')

    # add the directories and run the command
    remote_dir = '/global/cscratch1/sd/nhand/Research/eBOSS/measurements/'
    currdir = os.path.abspath('.') + os.path.sep
    dirs = [currdir, remote_dir]
    if path is not None:
        dirs[0] += path
        dirs[1] += path

        # append a backslash
        for i, d in enumerate(dirs):
            dirs[i] = os.path.abspath(d) + os.sep

    dirs[1] = "nhand@%s:%s" %(host, dirs[1])
    if direction == 'from':
        dirs = dirs[::-1]
    cmd += dirs

    ret = os.system(" ".join(cmd))

if __name__ == '__main__':

    desc = "sync the eBOSS measurements between utley and NERSC"
    parser = argparse.ArgumentParser(description=desc)

    h = 'the transfer direction; either `to` or `from` the remote host'
    parser.add_argument('direction', type=str, choices=['to', 'from'], help=h)

    h = 'the remote host; either `cori` or `edison`'
    parser.add_argument('host', type=str, choices=['cori', 'edison'], help=h)

    h = 'an additional subpath to sync only'
    parser.add_argument('-d', '--dir', type=str, help=h)

    h = 'show what would have been transferred'
    parser.add_argument('-n', '--dry-run', action='store_true', help=h)

    h = 'add the --delete tag'
    parser.add_argument('--delete', action='store_true', help=h)

    ns = parser.parse_args()
    sync(ns.direction, ns.host, path=ns.dir, dry_run=ns.dry_run, delete=ns.delete)
